api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

    show_webby: false
    title: 'SpeedTrack - API'
    description: 'An API-Based Internet Speed Monitoring Tool'
    version: '0.9.1-alpha'